version: '3.5'

services:
    postgres:
        container_name: postgres_container
        image: postgres
        env_file:
            - 'variables.env'
        volumes:
            - ./database/postgres_vol:/data/postgres
        ports:
            - 5432:5432
        networks:
            postgres:
                ipv4_address: 10.5.0.6
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        env_file:
            - 'variables.env'
        volumes:
            - ./database/pgadmin_vol:/var/lib/pgadmin
        ports:
            - 5050:80
        networks:
            - postgres
        restart: unless-stopped
    
    sumo:
        container_name: sumo_container
        build:
            app/sumo
        volumes:
            - ./app/sumo/sumo_vol:/home
        env_file:
            - 'variables.env'
        networks:
            - postgres
        command: tail -f /dev/null # keeping the container alive
        restart: unless-stopped

    backend:
        container_name: backend_container
        build:
            app/backend
        volumes:
            - ./app/backend/backend_vol:/home
        env_file:
            - 'variables.env'
        networks:
            - postgres
        command: tail -f /dev/null # keeping the container alive
        restart: unless-stopped


networks:
    postgres:
        driver: bridge
        ipam:
         config:
           - subnet: 10.5.0.0/16
             gateway: 10.5.0.1
